env: "local" # local, dev, prod

smpp:
  address: "smstv.gov.tm:5019"
  user: "Televid"
  password: "Te17evid"

database:
  address: "root:root@tcp(localhost:3306)/televid"

rabbitmq:
  url: "amqp://tpsuser:qazwsx12@216.250.13.30:5672/smstv"